version: "3.9"
services:
    web:
        build: .
        image: kreddo-int
        ports:
            - "8063:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - kreddo-int

    db:
        image: mysql:8
        environment:
            MYSQL_DATABASE: kreddo-int
            MYSQL_USER: laravel
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - kreddo-int

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "8064:80"
        depends_on:
            - db
        networks:
            - kreddo-int

networks:
    kreddo-int:
